global using NUnit.Framework;
global using Npgsql;
global using System;
global using System.Collections.Generic;
global using System.Data;
global using System.Linq;
global using System.Text;
global using System.Threading.Tasks;
global using System.Windows;